### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by PeterDavidCarter** [rubyandcoffee/online_pets#24]
While I appreciate it's probably just a case of cloning and running `rails server` with the correct params (I haven't tried yet), it would be useful to have installation instructions. Particularly for anyone who may not be familiar with the Rails environment but is still interested in the idea.

**Comment by rubyandcoffee** [comment]
Haha, I wouldn't bother - it's a private project from a long time ago that I was recently slowly improving because it's a very ugly, horrible app.
Since it's private, not including instructions is my way of discouraging people from going anywhere near it!
